# Generated by Django 4.2 on 2023-04-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
